title: Pokemon ShiningCrystal
description: A QOL hack of pokecrystal
social_link: patreon
social_username: brodmoran
github_repo: shiningcrystal
github_username: FieryMewtwo
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /dev_site
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
